import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/nav'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Jumbotron from '@/components/jumbotron'
import Why from '../components/why'
import Footer from '../components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       <Nav styles={styles}/>
       <Jumbotron/>
       <Why/>
       <Footer/>
      </main>
    </>
  )
}
