import React from 'react'
import Myform from '../../components/form.jsx'
import Head from 'next/head'
import styles from '../../styles/form.module.css'

export default function index() {
  return (
    <>
    <Head>
        <title>Form Aspirasi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <main className='container-md'>
      <section className={styles.formContainer}>
        <h1 className='text-center'>Suara Mahasiswa Prodi Kep. Anestesi</h1>
        <Myform 
          styles={styles}
        />
      </section>
    </main>
    </>
  )
}
