import React from 'react'
import Myform from '../../components/form.jsx'
import NavForm from '../../components/navForm.jsx'
import Head from 'next/head'
import styles from '../../styles/form.module.css'
import Layout from '@/layout/layout.jsx'

export default function index() {
  return (
    <>
    <Head>
        <title>Form Aspirasi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <Layout page='form'>
    
   
      <div className={`${styles.mainContent} d-flex`}>
        <div className={`${styles.leftContainer} d-flex`}>
          <div className={styles.infoContainer}>
            <section className={`${styles.descSection}`}>
              <h1 className='fw-bolder '>Share Your Thoughts</h1>
              <p>Punya Aspirasi yang ingin disampaikan pada prodi
                dan HMPS?<br/> Berikan aspirasimu disini!</p>
              <a href="#formSection" className={styles.formButton}>Beri aspirasi</a>
            </section>
            <section className={`${styles.socmedSection}`}>
              <h3 className='fw-bold mb-4'>Social Media</h3>
              <div className={`${styles.socmedList}`}>
                <a href="#" className='mb-3 text-decoration-underline'>Instagram</a>
                <a href="#" className='mb-3 text-decoration-underline'>Twitter</a>
                <a href="#" className='text-decoration-underline'>Facebook</a>

              </div>
            </section>
          </div>
        </div>
        <div className={`${styles.rightContainer}`} id='formSection'>
          <Myform styles={styles}/>
        </div>
      </div>
    </Layout>
    </>
  )
}
